name: Docker Build Code Server Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'

env:
  TZ: Asia/Shanghai
  REGISTRY: ghcr.io
  IMAGE_NAME: code-server
  IMAGE_TAGS: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build the Docker image
        run: |
          ROOT_PATH=$(pwd)
          for tag in ${IMAGE_TAGS}; do
            cd ${ROOT_PATH}/images/${{ env.IMAGE_NAME }}/${tag}
            docker build . -f Dockerfile -t ${{ secrets.DOCKER_REGISTRY }}/dockenv/${{ env.IMAGE_NAME }}:${tag}
          done

      - name: Login Github Package Registry
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p "${{ secrets.DOCKER_PASSWD }}" ${{ secrets.DOCKER_REGISTRY }}

      - name: Push Docker Image To Github Package
        run: |
          for tag in ${IMAGE_TAGS}; do
            docker push ${{ secrets.DOCKER_REGISTRY }}/dockenv/${{ env.IMAGE_NAME }}:${tag}
          done
